### ISSUE TITLE
不能在dropbox.com对jquery进行重定向

### ISSUE THREAD

**Issue by binyuj** [jiacai2050/gooreplacer4chrome#13]
重定向之后，由于dropbox.com的安全设置，浏览器会拒绝加载jquery。
貌似他们使用了某种黑科技，网页里面加了

```
<script nonce="Ec6bcxw46VgDO6OXsXQ5">
```

这段代码的原因
浏览器报错是：

```
Refused to load the script 'https://ajax.lug.ustc.edu.cn/ajax/libs/jquery/1.10.2/jquery.min.js' because it violates the following Content Security Policy directive: "script-src https://ajax.googleapis.com/ajax/libs/jquery/ 'unsafe-eval' 'self' https://cf.dropboxstatic.com/static/javascript/ https://cf.dropboxstatic.com/static/coffee/compiled/ https://www.dropboxstatic.com/static/javascript/ https://www.dropboxstatic.com/static/coffee/ https://www.google.com/recaptcha/api/ 'unsafe-inline'  'nonce-Ec6bcxw46VgDO6OXsXQ5' ".
```

**Comment by jiacai2050** [comment]
https://github.com/jiacai2050/gooreplacer/issues/14

**Comment by esec** [comment]
`Refused to load the script 'https://cdn.rawgit.com/jiacai2050/gooreplacer/gh-pages/proxy/api.js' because it violates the following Content Security Policy directive: "script-src 'nonce-Ea0qYYb9uyFN7p3jtQFeFwKvGGs' 'self' 'unsafe-eval' https://apis.google.com https://ssl.gstatic.com https://www.google.com https://www.gstatic.com".`
chrome 59.0.3071.86 插件版本0.9，现在打开在线规则貌似会影响到google首页notification的加载……

**Comment by jiacai2050** [comment]
可以在新版定义这么一条 response header 规则，

![image](https://user-images.githubusercontent.com/3848910/32360220-bcc19144-c08e-11e7-884f-798826c4256d.png)

去掉 `content-security-policy` 限制
